services:
  api:
    build: .
    ports:
      - "9137:9137"
    volumes:
      - .:/app
    environment:
      - MONGODB_USERNAME=colorin
      - MONGODB_PASSWORD=facilito!23
      - MONGODB_CLUSTER=colorin.uukmsjh.mongodb.net
      - MONGODB_DB_NAME=colorin
      - PORT=9137
    working_dir: /app
    restart: unless-stopped
    # command: >
    #   sh -c "uvicorn main:app --host 0.0.0.0 --port 9137 --reload"

  frontend:
    build:
      context: ./frontend
    ports:
      - "61234:61234"
    environment:
      - VITE_API_URL=http://localhost:9137
    depends_on:
      - api
